const admin = require('firebase-admin');
require('dotenv').config();
admin.initializeApp({ credential: admin.credential.cert({ projectId: process.env.FIREBASE_PROJECT_ID, clientEmail: process.env.FIREBASE_CLIENT_EMAIL, privateKey: process.env.FIREBASE_PRIVATE_KEY.replace(/\\n/g, '\n') }) });
const db = admin.firestore();
const universities = [
{ name: "Yale University", country: "USA", city: "New Haven, Connecticut", ranking: 5, tuition: 59950, acceptanceRate: 6, programs: ["Law", "Arts", "Medicine"], logo: "https://www.google.com/s2/favicons?domain=yale.edu&sz=128", website: "yale.edu", level: "UG,Masters,PhD" },
{ name: "Princeton University", country: "USA", city: "Princeton, New Jersey", ranking: 6, tuition: 57410, acceptanceRate: 6, programs: ["Engineering", "Science", "Arts"], logo: "https://www.google.com/s2/favicons?domain=princeton.edu&sz=128", website: "princeton.edu", level: "UG,Masters,PhD" },
{ name: "Columbia University", country: "USA", city: "New York, New York", ranking: 7, tuition: 63530, acceptanceRate: 7, programs: ["Business", "Law", "Medicine"], logo: "https://www.google.com/s2/favicons?domain=columbia.edu&sz=128", website: "columbia.edu", level: "UG,Masters,PhD" },
{ name: "University of Chicago", country: "USA", city: "Chicago, Illinois", ranking: 10, tuition: 61179, acceptanceRate: 7, programs: ["Business", "Economics", "Law"], logo: "https://www.google.com/s2/favicons?domain=uchicago.edu&sz=128", website: "uchicago.edu", level: "UG,Masters,PhD" },
{ name: "University of Pennsylvania", country: "USA", city: "Philadelphia, Pennsylvania", ranking: 12, tuition: 63452, acceptanceRate: 8, programs: ["Business", "Medicine", "Engineering"], logo: "https://www.google.com/s2/favicons?domain=upenn.edu&sz=128", website: "upenn.edu", level: "UG,Masters,PhD" },
{ name: "Cornell University", country: "USA", city: "Ithaca, New York", ranking: 13, tuition: 61015, acceptanceRate: 11, programs: ["Engineering", "Agriculture", "Arts"], logo: "https://www.google.com/s2/favicons?domain=cornell.edu&sz=128", website: "cornell.edu", level: "UG,Masters,PhD" },
{ name: "Johns Hopkins University", country: "USA", city: "Baltimore, Maryland", ranking: 9, tuition: 60480, acceptanceRate: 11, programs: ["Medicine", "Engineering", "Public Health"], logo: "https://www.google.com/s2/favicons?domain=jhu.edu&sz=128", website: "jhu.edu", level: "UG,Masters,PhD" },
{ name: "Duke University", country: "USA", city: "Durham, North Carolina", ranking: 15, tuition: 60244, acceptanceRate: 8, programs: ["Medicine", "Law", "Business"], logo: "https://www.google.com/s2/favicons?domain=duke.edu&sz=128", website: "duke.edu", level: "UG,Masters,PhD" },
{ name: "Northwestern University", country: "USA", city: "Evanston, Illinois", ranking: 16, tuition: 60768, acceptanceRate: 7, programs: ["Journalism", "Business", "Engineering"], logo: "https://www.google.com/s2/favicons?domain=northwestern.edu&sz=128", website: "northwestern.edu", level: "UG,Masters,PhD" },
{ name: "Dartmouth College", country: "USA", city: "Hanover, New Hampshire", ranking: 18, tuition: 61947, acceptanceRate: 9, programs: ["Business", "Arts", "Engineering"], logo: "https://www.google.com/s2/favicons?domain=dartmouth.edu&sz=128", website: "dartmouth.edu", level: "UG,Masters,PhD" },
{ name: "Brown University", country: "USA", city: "Providence, Rhode Island", ranking: 17, tuition: 62304, acceptanceRate: 8, programs: ["Arts", "Science", "Engineering"], logo: "https://www.google.com/s2/favicons?domain=brown.edu&sz=128", website: "brown.edu", level: "UG,Masters,PhD" },
{ name: "Vanderbilt University", country: "USA", city: "Nashville, Tennessee", ranking: 18, tuition: 54158, acceptanceRate: 11, programs: ["Medicine", "Law", "Education"], logo: "https://www.google.com/s2/favicons?domain=vanderbilt.edu&sz=128", website: "vanderbilt.edu", level: "UG,Masters,PhD" },
{ name: "Rice University", country: "USA", city: "Houston, Texas", ranking: 17, tuition: 52001, acceptanceRate: 11, programs: ["Engineering", "Science", "Architecture"], logo: "https://www.google.com/s2/favicons?domain=rice.edu&sz=128", website: "rice.edu", level: "UG,Masters,PhD" },
{ name: "Georgetown University", country: "USA", city: "Washington DC", ranking: 22, tuition: 59957, acceptanceRate: 14, programs: ["Law", "Foreign Service", "Business"], logo: "https://www.google.com/s2/favicons?domain=georgetown.edu&sz=128", website: "georgetown.edu", level: "UG,Masters,PhD" },
{ name: "University of California Berkeley", country: "USA", city: "Berkeley, California", ranking: 4, tuition: 44066, acceptanceRate: 17, programs: ["Engineering", "Business", "Law"], logo: "https://www.google.com/s2/favicons?domain=berkeley.edu&sz=128", website: "berkeley.edu", level: "UG,Masters,PhD" },
{ name: "University of California Los Angeles", country: "USA", city: "Los Angeles, California", ranking: 20, tuition: 42994, acceptanceRate: 14, programs: ["Film", "Engineering", "Medicine"], logo: "https://www.google.com/s2/favicons?domain=ucla.edu&sz=128", website: "ucla.edu", level: "UG,Masters,PhD" },
{ name: "University of Michigan", country: "USA", city: "Ann Arbor, Michigan", ranking: 23, tuition: 52266, acceptanceRate: 20, programs: ["Engineering", "Business", "Law"], logo: "https://www.google.com/s2/favicons?domain=umich.edu&sz=128", website: "umich.edu", level: "UG,Masters,PhD" },
{ name: "Carnegie Mellon University", country: "USA", city: "Pittsburgh, Pennsylvania", ranking: 22, tuition: 58924, acceptanceRate: 15, programs: ["Computer Science", "Engineering", "Arts"], logo: "https://www.google.com/s2/favicons?domain=cmu.edu&sz=128", website: "cmu.edu", level: "UG,Masters,PhD" },
{ name: "New York University", country: "USA", city: "New York, New York", ranking: 35, tuition: 55384, acceptanceRate: 21, programs: ["Business", "Arts", "Law"], logo: "https://www.google.com/s2/favicons?domain=nyu.edu&sz=128", website: "nyu.edu", level: "UG,Masters,PhD" },
{ name: "University of Southern California", country: "USA", city: "Los Angeles, California", ranking: 27, tuition: 60275, acceptanceRate: 16, programs: ["Film", "Business", "Engineering"], logo: "https://www.google.com/s2/favicons?domain=usc.edu&sz=128", website: "usc.edu", level: "UG,Masters,PhD" },
{ name: "Imperial College London", country: "UK", city: "London, England", ranking: 6, tuition: 35100, acceptanceRate: 15, programs: ["Engineering", "Medicine", "Science"], logo: "https://www.google.com/s2/favicons?domain=imperial.ac.uk&sz=128", website: "imperial.ac.uk", level: "UG,Masters,PhD" },
{ name: "University College London", country: "UK", city: "London, England", ranking: 8, tuition: 26200, acceptanceRate: 63, programs: ["Arts", "Engineering", "Medicine"], logo: "https://www.google.com/s2/favicons?domain=ucl.ac.uk&sz=128", website: "ucl.ac.uk", level: "UG,Masters,PhD" },
{ name: "London School of Economics", country: "UK", city: "London, England", ranking: 45, tuition: 22430, acceptanceRate: 16, programs: ["Economics", "Law", "Social Science"], logo: "https://www.google.com/s2/favicons?domain=lse.ac.uk&sz=128", website: "lse.ac.uk", level: "UG,Masters,PhD" },
{ name: "University of Edinburgh", country: "UK", city: "Edinburgh, Scotland", ranking: 22, tuition: 23100, acceptanceRate: 43, programs: ["Medicine", "Arts", "Engineering"], logo: "https://www.google.com/s2/favicons?domain=ed.ac.uk&sz=128", website: "ed.ac.uk", level: "UG,Masters,PhD" },
{ name: "University of Manchester", country: "UK", city: "Manchester, England", ranking: 28, tuition: 22000, acceptanceRate: 56, programs: ["Business", "Engineering", "Science"], logo: "https://www.google.com/s2/favicons?domain=manchester.ac.uk&sz=128", website: "manchester.ac.uk", level: "UG,Masters,PhD" },
{ name: "McGill University", country: "Canada", city: "Montreal, Quebec", ranking: 31, tuition: 20000, acceptanceRate: 46, programs: ["Medicine", "Law", "Engineering"], logo: "https://www.google.com/s2/favicons?domain=mcgill.ca&sz=128", website: "mcgill.ca", level: "UG,Masters,PhD" },
{ name: "University of British Columbia", country: "Canada", city: "Vancouver, British Columbia", ranking: 34, tuition: 36476, acceptanceRate: 52, programs: ["Engineering", "Forestry", "Medicine"], logo: "https://www.google.com/s2/favicons?domain=ubc.ca&sz=128", website: "ubc.ca", level: "UG,Masters,PhD" },
{ name: "University of Waterloo", country: "Canada", city: "Waterloo, Ontario", ranking: 112, tuition: 42000, acceptanceRate: 53, programs: ["Engineering", "Computer Science", "Mathematics"], logo: "https://www.google.com/s2/favicons?domain=uwaterloo.ca&sz=128", website: "uwaterloo.ca", level: "UG,Masters,PhD" },
{ name: "Australian National University", country: "Australia", city: "Canberra, ACT", ranking: 30, tuition: 38000, acceptanceRate: 35, programs: ["Science", "Arts", "Law"], logo: "https://www.google.com/s2/favicons?domain=anu.edu.au&sz=128", website: "anu.edu.au", level: "UG,Masters,PhD" },
{ name: "University of Sydney", country: "Australia", city: "Sydney, NSW", ranking: 38, tuition: 41000, acceptanceRate: 30, programs: ["Medicine", "Law", "Engineering"], logo: "https://www.google.com/s2/favicons?domain=sydney.edu.au&sz=128", website: "sydney.edu.au", level: "UG,Masters,PhD" },
{ name: "University of New South Wales", country: "Australia", city: "Sydney, NSW", ranking: 43, tuition: 40000, acceptanceRate: 40, programs: ["Engineering", "Business", "Law"], logo: "https://www.google.com/s2/favicons?domain=unsw.edu.au&sz=128", website: "unsw.edu.au", level: "UG,Masters,PhD" },
{ name: "EPFL", country: "Switzerland", city: "Lausanne, Vaud", ranking: 14, tuition: 1500, acceptanceRate: 22, programs: ["Engineering", "Science", "Technology"], logo: "https://www.google.com/s2/favicons?domain=epfl.ch&sz=128", website: "epfl.ch", level: "UG,Masters,PhD" },
{ name: "Nanyang Technological University", country: "Singapore", city: "Singapore", ranking: 19, tuition: 17550, acceptanceRate: 22, programs: ["Engineering", "Business", "Science"], logo: "https://www.google.com/s2/favicons?domain=ntu.edu.sg&sz=128", website: "ntu.edu.sg", level: "UG,Masters,PhD" },
{ name: "Kyoto University", country: "Japan", city: "Kyoto", ranking: 35, tuition: 5200, acceptanceRate: 28, programs: ["Science", "Engineering", "Medicine"], logo: "https://www.google.com/s2/favicons?domain=kyoto-u.ac.jp&sz=128", website: "kyoto-u.ac.jp", level: "UG,Masters,PhD" },
{ name: "Indian Institute of Technology Delhi", country: "India", city: "New Delhi", ranking: 185, tuition: 2200, acceptanceRate: 2, programs: ["Engineering", "Technology", "Science"], logo: "https://www.google.com/s2/favicons?domain=iitd.ac.in&sz=128", website: "iitd.ac.in", level: "UG,Masters,PhD" },
{ name: "University of Hong Kong", country: "Hong Kong", city: "Hong Kong", ranking: 26, tuition: 14000, acceptanceRate: 15, programs: ["Medicine", "Business", "Law"], logo: "https://www.google.com/s2/favicons?domain=hku.hk&sz=128", website: "hku.hk", level: "UG,Masters,PhD" },
{ name: "KU Leuven", country: "Belgium", city: "Leuven, Flemish Brabant", ranking: 71, tuition: 1000, acceptanceRate: 40, programs: ["Engineering", "Medicine", "Law"], logo: "https://www.google.com/s2/favicons?domain=kuleuven.be&sz=128", website: "kuleuven.be", level: "UG,Masters,PhD" },
{ name: "University of Amsterdam", country: "Netherlands", city: "Amsterdam, North Holland", ranking: 55, tuition: 2209, acceptanceRate: 50, programs: ["Business", "Law", "Arts"], logo: "https://www.google.com/s2/favicons?domain=uva.nl&sz=128", website: "uva.nl", level: "UG,Masters,PhD" },
{ name: "Delft University of Technology", country: "Netherlands", city: "Delft, South Holland", ranking: 47, tuition: 2209, acceptanceRate: 40, programs: ["Engineering", "Architecture", "Technology"], logo: "https://www.google.com/s2/favicons?domain=tudelft.nl&sz=128", website: "tudelft.nl", level: "UG,Masters,PhD" },
{ name: "University of Cape Town", country: "South Africa", city: "Cape Town, Western Cape", ranking: 226, tuition: 8000, acceptanceRate: 12, programs: ["Medicine", "Engineering", "Law"], logo: "https://www.google.com/s2/favicons?domain=uct.ac.za&sz=128", website: "uct.ac.za", level: "UG,Masters,PhD" },
{ name: "Trinity College Dublin", country: "Ireland", city: "Dublin", ranking: 81, tuition: 18000, acceptanceRate: 30, programs: ["Arts", "Engineering", "Medicine"], logo: "https://www.google.com/s2/favicons?domain=tcd.ie&sz=128", website: "tcd.ie", level: "UG,Masters,PhD" },
{ name: "University of São Paulo", country: "Brazil", city: "São Paulo", ranking: 97, tuition: 0, acceptanceRate: 15, programs: ["Medicine", "Engineering", "Law"], logo: "https://www.google.com/s2/favicons?domain=usp.br&sz=128", website: "usp.br", level: "UG,Masters,PhD" },
{ name: "UNAM", country: "Mexico", city: "Mexico City", ranking: 105, tuition: 0, acceptanceRate: 10, programs: ["Medicine", "Law", "Engineering"], logo: "https://www.google.com/s2/favicons?domain=unam.mx&sz=128", website: "unam.mx", level: "UG,Masters,PhD" },
{ name: "Lomonosov Moscow State University", country: "Russia", city: "Moscow", ranking: 87, tuition: 8000, acceptanceRate: 20, programs: ["Science", "Arts", "Engineering"], logo: "https://www.google.com/s2/favicons?domain=msu.ru&sz=128", website: "msu.ru", level: "UG,Masters,PhD" },
{ name: "Hebrew University of Jerusalem", country: "Israel", city: "Jerusalem", ranking: 133, tuition: 12000, acceptanceRate: 20, programs: ["Medicine", "Science", "Arts"], logo: "https://www.google.com/s2/favicons?domain=huji.ac.il&sz=128", website: "huji.ac.il", level: "UG,Masters,PhD" },
{ name: "King Abdullah University of Science and Technology", country: "Saudi Arabia", city: "Thuwal", ranking: 99, tuition: 0, acceptanceRate: 15, programs: ["Science", "Engineering", "Technology"], logo: "https://www.google.com/s2/favicons?domain=kaust.edu.sa&sz=128", website: "kaust.edu.sa", level: "Masters,PhD" },
{ name: "University of Malaya", country: "Malaysia", city: "Kuala Lumpur", ranking: 65, tuition: 5000, acceptanceRate: 20, programs: ["Engineering", "Medicine", "Business"], logo: "https://www.google.com/s2/favicons?domain=um.edu.my&sz=128", website: "um.edu.my", level: "UG,Masters,PhD" },
{ name: "Chulalongkorn University", country: "Thailand", city: "Bangkok", ranking: 201, tuition: 3000, acceptanceRate: 20, programs: ["Medicine", "Engineering", "Business"], logo: "https://www.google.com/s2/favicons?domain=chula.ac.th&sz=128", website: "chula.ac.th", level: "UG,Masters,PhD" },
{ name: "University of Indonesia", country: "Indonesia", city: "Depok, West Java", ranking: 237, tuition: 3000, acceptanceRate: 10, programs: ["Medicine", "Engineering", "Law"], logo: "https://www.google.com/s2/favicons?domain=ui.ac.id&sz=128", website: "ui.ac.id", level: "UG,Masters,PhD" },
{ name: "University of the Philippines", country: "Philippines", city: "Quezon City", ranking: 351, tuition: 500, acceptanceRate: 10, programs: ["Engineering", "Medicine", "Law"], logo: "https://www.google.com/s2/favicons?domain=up.edu.ph&sz=128", website: "up.edu.ph", level: "UG,Masters,PhD" },
{ name: "Pontifical Catholic University of Chile", country: "Chile", city: "Santiago", ranking: 121, tuition: 10000, acceptanceRate: 20, programs: ["Engineering", "Medicine", "Law"], logo: "https://www.google.com/s2/favicons?domain=uc.cl&sz=128", website: "uc.cl", level: "UG,Masters,PhD" },
{ name: "Universidad de los Andes Colombia", country: "Colombia", city: "Bogotá", ranking: 230, tuition: 15000, acceptanceRate: 25, programs: ["Engineering", "Business", "Law"], logo: "https://www.google.com/s2/favicons?domain=uniandes.edu.co&sz=128", website: "uniandes.edu.co", level: "UG,Masters,PhD" },
{ name: "Qatar University", country: "Qatar", city: "Doha", ranking: 441, tuition: 0, acceptanceRate: 25, programs: ["Engineering", "Business", "Law"], logo: "https://www.google.com/s2/favicons?domain=qu.edu.qa&sz=128", website: "qu.edu.qa", level: "UG,Masters,PhD" },
{ name: "University of Ghana", country: "Ghana", city: "Accra", ranking: 801, tuition: 2000, acceptanceRate: 30, programs: ["Business", "Law", "Science"], logo: "https://www.google.com/s2/favicons?domain=ug.edu.gh&sz=128", website: "ug.edu.gh", level: "UG,Masters,PhD" },
{ name: "University of Lagos", country: "Nigeria", city: "Lagos", ranking: 801, tuition: 1000, acceptanceRate: 30, programs: ["Medicine", "Law", "Engineering"], logo: "https://www.google.com/s2/favicons?domain=unilag.edu.ng&sz=128", website: "unilag.edu.ng", level: "UG,Masters,PhD" },
{ name: "Makerere University", country: "Uganda", city: "Kampala", ranking: 801, tuition: 1200, acceptanceRate: 20, programs: ["Medicine", "Engineering", "Arts"], logo: "https://www.google.com/s2/favicons?domain=mak.ac.ug&sz=128", website: "mak.ac.ug", level: "UG,Masters,PhD" },
{ name: "American University of Beirut", country: "Lebanon", city: "Beirut", ranking: 401, tuition: 25000, acceptanceRate: 30, programs: ["Medicine", "Engineering", "Business"], logo: "https://www.google.com/s2/favicons?domain=aub.edu.lb&sz=128", website: "aub.edu.lb", level: "UG,Masters,PhD" },
{ name: "University of Auckland", country: "New Zealand", city: "Auckland", ranking: 65, tuition: 28000, acceptanceRate: 55, programs: ["Engineering", "Business", "Medicine"], logo: "https://www.google.com/s2/favicons?domain=auckland.ac.nz&sz=128", website: "auckland.ac.nz", level: "UG,Masters,PhD" },
{ name: "Technion Israel Institute of Technology", country: "Israel", city: "Haifa", ranking: 77, tuition: 10000, acceptanceRate: 15, programs: ["Engineering", "Science", "Technology"], logo: "https://www.google.com/s2/favicons?domain=technion.ac.il&sz=128", website: "technion.ac.il", level: "UG,Masters,PhD" },
{ name: "Cairo University", country: "Egypt", city: "Giza", ranking: 401, tuition: 500, acceptanceRate: 30, programs: ["Medicine", "Law", "Engineering"], logo: "https://www.google.com/s2/favicons?domain=cu.edu.eg&sz=128", website: "cu.edu.eg", level: "UG,Masters,PhD" },
{ name: "Khalifa University", country: "UAE", city: "Abu Dhabi", ranking: 201, tuition: 0, acceptanceRate: 20, programs: ["Engineering", "Science", "Technology"], logo: "https://www.google.com/s2/favicons?domain=ku.ac.ae&sz=128", website: "ku.ac.ae", level: "UG,Masters,PhD" },
{ name: "Vietnam National University Hanoi", country: "Vietnam", city: "Hanoi", ranking: 801, tuition: 1000, acceptanceRate: 20, programs: ["Engineering", "Science", "Business"], logo: "https://www.google.com/s2/favicons?domain=vnu.edu.vn&sz=128", website: "vnu.edu.vn", level: "UG,Masters,PhD" },
{ name: "University of Dhaka", country: "Bangladesh", city: "Dhaka", ranking: 801, tuition: 200, acceptanceRate: 10, programs: ["Arts", "Science", "Business"], logo: "https://www.google.com/s2/favicons?domain=du.ac.bd&sz=128", website: "du.ac.bd", level: "UG,Masters,PhD" },
{ name: "Tribhuvan University", country: "Nepal", city: "Kathmandu", ranking: 1001, tuition: 300, acceptanceRate: 25, programs: ["Science", "Arts", "Engineering"], logo: "https://www.google.com/s2/favicons?domain=tribhuvan-university.edu.np&sz=128", website: "tribhuvan-university.edu.np", level: "UG,Masters,PhD" },
{ name: "University of Colombo", country: "Sri Lanka", city: "Colombo", ranking: 1001, tuition: 300, acceptanceRate: 10, programs: ["Arts", "Medicine", "Law"], logo: "https://www.google.com/s2/favicons?domain=cmb.ac.lk&sz=128", website: "cmb.ac.lk", level: "UG,Masters,PhD" }
];

async function seed() {
  const snap = await db.collection('universities').get();
  const existing = new Set();
  snap.forEach(doc => existing.add(doc.data().name));
  console.log('Existing:', existing.size);
  let added = 0, skipped = 0;
  for (const uni of universities) {
    if (existing.has(uni.name)) { skipped++; continue; }
    await db.collection('universities').add({...uni, createdAt: new Date()});
    added++;
    console.log('✅ ' + added + ' - ' + uni.name);
  }
  console.log('\n🎉 Done! Added: ' + added + ', Skipped: ' + skipped);
  process.exit(0);
}
seed().catch(e => { console.error('❌', e.message); process.exit(1); });
